### ISSUE TITLE
broken DOI pattern

### ISSUE THREAD

**Issue by rerickson-usgs** [mnfienen/quarto-utils#5]
@mnfienen  These DOIs don't work:

1. [\_doi:https://doi.org/10.1577/1548-8659(2001)130<0809:SVIDOL>2.0.CO;2]
2. [\_doi:https://doi.org/10.1641/0006-3568(2000)050[0053:EAECON]2.3.CO;2]
3. [\_doi:https://doi.org/10.1890/1051-0761(2006)016[2035:BIRFUP]2.0.CO;2]

Number 1 because of `<` and `>` I guess and Numbers 2 and 3 because of `[`, `]`, and maybe `(`, and `)`. Also, `;` might not be playing nice. I'm not sure how to fix.

**Comment by mnfienen** [comment]
@rerickson-usgs - I think these are both issues with the `;` character. I have an idea that might be a fix. Stay tuned :)

**Comment by mnfienen** [comment]
ok @rerickson-usgs ---- this is fixed now in commit f1b9dfd
