### ISSUE TITLE
SSL fail, loud rather than quite

### ISSUE THREAD

**Issue by rerickson-usgs** [mnfienen/quarto-utils#6]
On the USGS network when using `update_refs.py` I get 

```{bash} $python update_refs.py il_gradient.qmd references.bib 
update_refs.py
il_gradient.qmd
no dois found. No updates to make.
```

But, I had updates. When I debug by running with Python, I get:

```{python}
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)>
```

Feature request is have this fail "loudly" rather than quietly fail.

**Comment by mnfienen** [comment]
Good idea - now conveying the specific error. Should work if you pull the latest
